### ISSUE TITLE
Idea Tracker

### ISSUE THREAD

**Issue by DannielK** [DannielK/Cloudflare_CV#2]
Following are potential ideas to implement:

- [ ] Sticky sidebar content timeline scroller that skips to sections
- [ ] Add downloadable resume
- [ ] Visual skill list (maybe add proficiency %)
- [ ] Animations (tbd)

**Comment by DannielK** [comment]
- [ ] Add working email section?
- [ ] Add cool background animation for home page (maybe even for entire page)

**Comment by DannielK** [comment]
- [ ] Replace footer msg with a quote?
